name: Copilot setup steps

on:
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Ensure pnpm & Node are available for the agent’s environment
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # (Optional) If repo is empty, create a placeholder README so the agent can push branches/PRs
      - name: Ensure README exists
        run: |
          if [ ! -f README.md ]; then
            echo "# MTG CSV Viewer" > README.md
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: add README placeholder"
            git push || true
          fi
